dependencies:
  post:
    - ./bin/cisetup

checkout:
  post:
    - git fetch origin --depth=1000000

version: 2
jobs:

  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: circleci/postgres:9.4.12-alpine
    dependencies:
      post:
        - ./bin/cisetup

    checkout:
      post:
        - git fetch origin --depth=1000000
    steps:
      - dependencies
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: rails-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: sudo apt-get install cmake
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load


      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
